#!/usr/bin/env sh

# Generate the desktop theme from a wallpaper using Matugen or Wallust.
#
# Matugen uses the main config:
#     ~/.config/matugen/config.toml
#
# That config can generate themes for:
#     - Quickshell
#     - Kitty
#     - Hyprland
#     - GTK 3/4
#     - Rofi
#     - Walker
#     - Code-OSS / VS Code
#     - SwayNC
#     - Waybar
#     - and any other configured templates.
#
# This script does NOT switch Quickshell into wallpaper mode itself.
# The wallpaper theme file generated by Matugen is watched by Quickshell.
#
# To regenerate the full desktop theme:
#     ~/.config/quickshell/theme-switcher/wallpaper-theme/set.sh <image>
#
# Force a specific tool:
#     WALLPAPER_THEME_TOOL=matugen
#     WALLPAPER_THEME_TOOL=wallust
#
# Default:
#     WALLPAPER_THEME_TOOL=auto

set -eu

img=${1:-}

[ -n "$img" ] || {
    echo "set.sh: usage: set.sh <image>" >&2
    exit 1
}

[ -f "$img" ] || {
    echo "set.sh: no such image: $img" >&2
    exit 1
}

tool=${WALLPAPER_THEME_TOOL:-auto}

# Main Matugen configuration.
#
# This is intentionally NOT the local:
#   theme-switcher/wallpaper-theme/matugen/config.toml
#
# because we want Matugen to render the entire desktop.
MATUGEN_CONFIG="$HOME/.config/matugen/config.toml"

run_matugen() {
    echo "=== DEBUG ==="
    echo "PATH=$PATH"
    echo "matugen=$(command -v matugen)"
    echo "img=$img"
    echo "config=$MATUGEN_CONFIG"

    matugen --version

    matugen image "$img" \
        -c "$MATUGEN_CONFIG" \
        -m dark \
        --type scheme-tonal-spot \
        --source-color-index 0 \
        -v
}
run_wallust() {
    dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)

    wallust run "$img" \
        -d "$dir/wallust" \
        -s \
        -q
}

case "$tool" in
    matugen)
        run_matugen
        ;;

    wallust)
        run_wallust
        ;;

    auto)
        if command -v matugen >/dev/null 2>&1; then
            run_matugen
        elif command -v wallust >/dev/null 2>&1; then
            run_wallust
        else
            echo "set.sh: need matugen or wallust installed" >&2
            exit 1
        fi
        ;;

    *)
        echo "set.sh: unknown WALLPAPER_THEME_TOOL=$tool" >&2
        exit 1
        ;;
esac